### PR TITLE
Add schema pain.001.003.03

### LINKED ISSUE #20: Support more SEPA versions?
What is the primary obstacle to increasing the set of supported SEPA PAIN versions?
For example https://github.com/raphaelm/python-fints/blob/18e361ab2c5beeddf126a601bfcc7753cf84efec/fints/client.py#L732 may choose `pain.001.003.03` which I guess worked before schema validation was introduced, but fails now, because that schema is not in `schemas/`.
Is it enough to drop the XSD file there, or are there more required steps?

### PR DESCRIPTION
**Pull request by tloebhard**
Added [pain.001.003.03.xsd](https://github.com/raphaelm/python-sepaxml/blob/master/sepaxml/schemas/pain.001.003.03.xsd) as a copy of [pain.001.001.03.xsd](https://github.com/raphaelm/python-sepaxml/blob/master/sepaxml/schemas/pain.001.001.03.xsd) (with adjusted namespace). Fixes #20

### CODE REVIEW

**Comment by MoritzFago** [comment]
What's the status on this? This missing currently breaks sepa transfers for byro-fints.

**Comment by tloebhard** [comment]
@MoritzFago does my pull request (adding just the file...) also fix your issue?

**Comment by raphaelm** [comment]
Sorry for not merging this, just copying the file and renaming it doesn't feel right, we should actually use the correct schema. See df5eb8d

**Comment by tloebhard** [comment]
> Sorry for not merging this, just copying the file and renaming it doesn't feel right, we should actually use the correct schema. See [df5eb8d](https://github.com/raphaelm/python-sepaxml/commit/df5eb8dbb8d9bf1b1dbfb906541d1aabcee72f6b)

Indeed, that was no famous solution - just pragmatic, as explained in #20 .

Thank you for solving!

**Pull request closed without merging**
